# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ae1c37290f62fee28617ff45e3359030dfb29673f0eaf2c0bdd3f166048d735f5ed45a4477a941c08659ecb539eb7db5736d8d617b079b0efcad3dd7b233c45

test:
  secret_key_base: 439c98575750ed87f91bafcb39fe1dee881d910364462bdc4e75269b202d4c332eed2ab7cbbc39b97194eb372e3f6ef9a6f64c6e74d972715725832674054b54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
